creation_rules:
  - path_regex: '\.env$'
    age: >-
      age1zptpgxhs9chnkudu69qut2hn706pmyngasvaz4ppf452un2x7p2ss6j96f,
      age15j0hsfgz0ru2ampfc7kt950gqzsfcgwejz2wctde0jeu8ky8k30qwmqwu0,
      age1psmayn76drks67a493l46gnuruaj7yw6u5qa043pqwg59596qq9sfh6etd,
      age1xwekswqnd6thy2rygk5k7d3c6e85z4vl4l79j7am5mv7nldn7cls2ejraa,
      age1xrl5h3076kq470ce68s2h5cevqx2zf2j38acjmrmkq2c23ycduksu7qym4


# 1. Ayushman
# 2. Vivek
# 3. Karan 
# 4. Krishnendu Dutta
# 5. Sandipan